version: '3.7'
services:
    reverse-proxy:
        image: traefik:latest
        command:
            - "--api"
            - "--defaultentrypoints=http"
            - "--docker"
            - "--docker.domain=localhost"
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - public-access
    search:
        labels:
            - "traefik.pre.frontend.rule=Host:pre.localhost;Method:Post;Path:/rest/_search"
    website:
        build:
            context: .
            target: prod
            network: host
        labels:
            - "traefik.pre.frontend.rule=Host:pre.localhost"
networks:
  public-access:
    driver: bridge
    name: public-access