version: '3.7'
services:
    website:
        build:
            target: dev
        volumes:
            - ./app:/usr/src/app/app
            - ./index.ejs:/usr/src/app/index.ejs
        labels:
            - "traefik.basic.port=8080"
