version: '3.7'
services:
    reverse-proxy:
        image: traefik:latest
        command:
            - "--api"
            - "--defaultentrypoints=http"
            - "--docker"
            - "--docker.domain=localhost"
        ports:
            - 80:80
            - 8181:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    search:
        image: mosuka/blast:v0.3.2
        restart: always
        environment:
            BLAST_BIND_ADDR: search:10000
            BLAST_GRPC_ADDR: search:10001
            BLAST_HTTP_ADDR: search:10002
            BLAST_RAFT_NODE_ID: node1
            BLAST_RAFT_DIR: /search/node1/raft
            BLAST_STORE_DIR: /search/node1/store
            BLAST_INDEX_DIR: /search/node1/index
            BLAST_INDEX_MAPPING: /search/index_mapping.json
        volumes:
            - ./search:/search
        command: start
        labels:
            - "traefik.enable=true"
            - "traefik.basic.port=10002"
            - "traefik.basic.protocol=http"
            - "traefik.basic.frontend.rule=Host:www.localhost;Method:Post;Path:/rest/_search"
    website:
        build:
            context: .
            target: prod
            network: host
        links:
            - search:search
        labels:
            - "traefik.enable=true"
            - "traefik.basic.port=8080"
            - "traefik.basic.protocol=http"
            - "traefik.basic.frontend.rule=Host:www.localhost"
